redirectMapping: /
redirectHost: http://localhost:4200
clientId: kaliekishop
clientSecret: zYjudZY6o29waXGPtzpEVFlniKEhZAnucK37YAbAwy_SK9wJNwpZacqqdHT_iHoyuIUiY5rOwpkJHvAbDayk3A

---

spring:
  profiles: azure




redirectMapping: /
redirectHost: http://40.71.86.58
clientId: HackGenome
clientSecret: K6Qt20cZFKV73VBaID5Yha3EYFtoIGIMPiNSXulOkoC4Gmi7RCT__bwUzFiCLFUlDSjWI17mHtwVgM-ConSswA
server:
  port: 80